apiVersion: v1
kind: Pod
metadata:
  name: logging-example
spec:
  containers:
  - name: busybox-simple-container
    image: busybox
    args:
    - /bin/sh
    - -c
    - >
      i=0;
      while true;
      do
        echo "$i: $(date)" >> /var/log/server.log;
        i=$((i+1));
        sleep 5;
      done
    volumeMounts:
    - name: logdir
      mountPath: /var/log
    resources: {}

  - name: log-reader
    image: busybox
    command: ["sh", "-c"]
    args:
    - tail -f /var/log/server.log
    volumeMounts:
    - name: logdir
      mountPath: /var/log
    resources: {}

  volumes:
  - name: logdir
    emptyDir: {}
